### ISSUE TITLE
ReactClipboard requires internet connection

### ISSUE THREAD

**Issue by sergey-lapin** [lapanoid/redux-import-export-monitor#2]
http://dl2.joxi.net/drive/0010/3977/692105/150812/9f6a960785.jpg

**Comment by calesce** [comment]
Hey, I pushed up a new version of the monitor. Uses the new DevTools API and acts like `Window.prompt()`. Since the input is automatically highlighted, it's probably easier to just copy the input instead of using ZeroClipboard.

**Comment by sergey-lapin** [comment]
@calesce Guess you are right, one problem less=)
