### ISSUE TITLE
async tasks

### ISSUE THREAD

**Issue by kjr247** [lapanoid/redux-import-export-monitor#5]
My guess with this one is that it doesn't handle Async tasks gracefully. I try to import the app state(which is quite large), by pasting it in and then tapping ESC, which is the only input key I've found to be successful, (enter just refreshed the page).

So at this point it starts trying to fire off all of the initial async calls to get the data for the page. These fire off and resolve several times and end with "TypeError: <object>.get is not a function" and then "Interrupted by an error up the chain" on the following states. I'm not sure if this is relevant, but I am using redux devtools along side it by using createDevTools twice and just giving it a separate name to be used.

**Comment by calesce** [comment]
Hey, this is still fairly experimental, we should note that in the README. I wouldn't think that having two DevTools instances would be a problem, but might be wrong. Can you reproduce with just the import-export monitor?

As far as async actions go, I've only used this monitor on the app I'm working on,which so far only has synchronous actions, so that's clearly a use case we need to test out more.

**Comment by kjr247** [comment]
Yes, I did try this originally without the redux devtools and it looked to be doing the same thing. I then used redux devtools to look more closely.

It could also really be anything at this point considering the app state has built up to be over 250,000 characters.

**Comment by calesce** [comment]
Hi, so you if were able to reproduce the error without Redux DevTools, then it seems like it's a problem with your app. "Interrupted by an error up the chain" usually means that there's an exception in your app, so I'd recommend looking at the stack trace to see where it's coming from.

Feel free to re-open if you think the problem has something to do with this monitor.

**Comment by kjr247** [comment]
Ok when I said that it looked to be doing the same thing without redux devtools, what I meant although very unclear in retrospect, was that the error only occurred when using redux-import-export-monitor.
